### ISSUE TITLE
A more detailed setup and run guide

### ISSUE THREAD

**Issue by rockdrigoma** [UKPLab/plms-graph2text#4]
I am trying to set this up but after cloning and running:
`./preprocess_WEBNLG.sh webnlg`

I got:
`FileNotFoundError: [Errno 2] No such file or directory: 'webnlg/test/testdata_with_lex.xml'`

How can I generate that file?
Are there any other steps I am missing?
It seems that after that one, I will need the unseen xml file as well.

**Comment by leoribeiro** [comment]
Hi @rockdrigoma, you need to download the dataset from https://gitlab.com/shimorina/webnlg-dataset/-/tree/master/webnlg_challenge_2017. After that, you should call the preprocessing script:
`./preprocess_WEBNLG.sh webnlg`, where `webnlg` is the folder containing the dataset.

**Comment by rockdrigoma** [comment]
Thank you, that worked!!
